### ISSUE TITLE
`README.md` could need a small example

### ISSUE THREAD

**Issue by Ocramius** [samrap/gestalt#19]
Without digging into the docs, it is hard to understand what this package is for. A small example at the top of `README.md` would increase visibility by A LOT.

**Comment by samrap** [comment]
I've actually been trying to do this for a few days now. The problem is I want to show some of the more advanced features like loaders and observers, without having too much code in the readme. As someone who came here having no idea what this was, how much code would you like to see in the readme?

**Comment by Ocramius** [comment]
Just what this does - very simple stuff. It is vital to give the reader an
idea of what the library is about.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by samrap** [comment]
Cool, will work on adding that in. Thank you!

**Comment by samrap** [comment]
Added for 0.3 branch https://github.com/samrap/gestalt/commit/3847edeaa219e53e0698a540fd2d408f33670c23
